---
- hosts: 
    192.168.17.137

  roles:
    - role: roman.redis-sentinel
      redis_sentinel_port: 26379
      bind: 0.0.0.0

    - role: roman.redis-sentinel
      redis_sentinel_port: 26380
      bind: 0.0.0.0


    - role: roman.redis
      bind: 127.0.0.1
      redis_port: 6379
      replication:
        master_name: MyMaster
        master_password: ala ma kota
        sentinels:
          - host: 127.0.0.1
            redis_sentinel_port: 26379
          - host: 127.0.0.1
            redis_sentinel_port: 26380


      