---
- hosts: all
  serial: 1

  roles:
    # works as designed, disabling execution
    # - role: roman.redis-sentinel
    #   redis_sentinel_port: 26379
    #   bind: 0.0.0.0

    # - role: roman.redis-sentinel
    #   redis_sentinel_port: 26380
    #   bind: 0.0.0.0


    - name: first instance
      role: roman.redis
      bind: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      redis_port: 6379
      redis_auth: 'alamakota'
      redis_configuration: | 
        slave-priority 200
      redis_replication:
        quorum: 2
        master_name: MyMaster1
        sentinels:
          - host: 192.168.17.131
            redis_sentinel_port: 26379
          - host: 192.168.17.137
            redis_sentinel_port: 26379

    - name: second instance
      role: roman.redis
      bind: 0.0.0.0
      redis_port: 6380
      redis_auth: 'alamakota'
      redis_configuration: | 
        slave-priority 200
      redis_replication:
        quorum: 2
        master_name: MyMaster2
        sentinels:
          - host: 192.168.17.131
            redis_sentinel_port: 26379
          - host: 192.168.17.137
            redis_sentinel_port: 26379
        
        