---
- hosts: redis

  roles:
    - role: roman.redis-sentinel
      redis_sentinel_port: 26379
      bind: 0.0.0.0

    - role: roman.redis-sentinel
      redis_sentinel_port: 26380
      bind: 0.0.0.0


    # - role: roman.redis
    #   bind: 127.0.0.1
    #   replication:
    #     master_name: MyMaster
    #     master_password: ala ma kota
    #     sentinels:
    #       - 127.0.0.1:26379


      