---
# tasks file for roman.redis-sentinel

- name: install epel-release repository
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: install redis sentinel
  package:
    name: 'redis-{{ version }}'
    state: present

- name: add config file
  template:
    backup: yes
    dest: "/etc/redis-sentinel-{{ redis_sentinel_port }}.conf"
    src: "redis-sentinel.conf"
    group: root
    owner: redis
    force: no
  register: redis_config_changed

- name: add service configuration
  template:
    backup: yes
    dest: "/usr/lib/systemd/system/redis-sentinel-{{ redis_sentinel_port }}.service"
    src: redis-sentinel.service
    group: root
    owner: redis
  register: redis_service_changed
  
- name: (re)start sentinel service
  service:
    name: "redis-sentinel-{{ redis_sentinel_port }}"
    state: "{{ 'restarted' if redis_config_changed.changed or redis_service_changed.changed else 'started' }}"
    enabled: true

- debug: msg="redis_sentinel_port={{ redis_sentinel_port }}"
  run_once: true