---
# tasks file for roman.redis-sentinel

- name: install epel-release repository
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: install redis
  package:
    name: 'redis-{{ version }}'
    state: present

- name: Create tmp directory
  file: 
    path: /tmp/redis_sentinel_{{ redis_sentinel_port }} 
    state: directory
    group: root
    owner: redis

- name: add config
  template:
    backup: yes
    dest: '/etc/redis-sentinel-{{ redis_sentinel_port }}.conf'
    src: 'redis-sentinel.conf'
    group: root
    owner: redis
    # force: no

- name: add service configuration
  template:
    backup: yes
    dest: '/usr/lib/systemd/system/redis-sentinel-{{ redis_sentinel_port }}.service'
    src: 'redis-sentinel.service'
    group: root
    owner: redis
    # force: no

- name: start sentinel serice
  service:
    name: 'redis-sentinel-{{ redis_sentinel_port }}'
    state: started


- debug:
    msg: "System {{ inventory_hostname }} has bind {{ bind }}"

# - name: install redis
#   package:
#     name: 'redis-{{ version }}'
#     state: absent